apiVersion: v1
kind: Service
metadata:
  name: tomcatmavenapp-service
  namespace: default
spec:
  selector:
    app: tomcatmavenapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
